language: scala
sudo: false
dist: trusty
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC1
jdk:
  - oraclejdk8
  - openjdk8
script: sbt "++${TRAVIS_SCALA_VERSION}!" test publishLocal
matrix:
  include:
  - scala: 2.12.8
    jdk: oraclejdk11
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
