language: scala
sudo: false
dist: trusty
scala:
  - 2.11.12
  - 2.12.12
  - 2.13.3
jdk:
  - oraclejdk8
  - openjdk8
script: sbt "++${TRAVIS_SCALA_VERSION}!" test publishLocal
matrix:
  include:
  - scala: 2.12.12
    jdk: openjdk11
  - os: windows
    language: bash
    env: JDK="adopt@1.8.0-272"
    before_install:
    - wget https://raw.githubusercontent.com/DanySK/Gravis-CI/c8f400623d8f756ef7c/.install-jdk-travis.sh
    - source .install-jdk-travis.sh
    script:
    - wget https://raw.githubusercontent.com/paulp/sbt-extras/4d558c88ae6ae240/sbt && chmod +x ./sbt
    - ./sbt "++ 2.13.3!" test
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
  - "$HOME/.cache/coursier/v1"
before_cache:
- find $HOME/.sbt -name "*.lock" | xargs rm
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
