before_script:
 - "echo $JAVA_OPTS"
 - "export JAVA_OPTS='-Xmx512m -Xss1M -XX:+CMSClassUnloadingEnabled -XX:MaxPermSize=256M'"
language: scala
scala:
  - 2.9.3
  - 2.10.3
jdk:
  - openjdk6

notifications:
  email: false